all: Indigo_Star_Enterprises

Indigo_Star_Enterprises: main.cpp Compressor.h Compressor.cpp CoolingUnit.h CoolingUnit.cpp AirConditioner.h AirConditioner.cpp Freezer.h Freezer.cpp
	g++ -o "Indigo_Star_Enterprises" main.cpp Compressor.cpp CoolingUnit.cpp AirConditioner.cpp Freezer.cpp

clean:
	rm -f "Indigo_Star_Enterprises"