all: ./main.cpp ./platform.h ./platform.cpp ./person.h ./person.cpp ./publisher.h ./publisher.cpp ./subscriber.h ./subscriber.cpp
	g++ -o "./PubSub_Platform" ./main.cpp ./platform.cpp ./person.cpp ./publisher.cpp ./subscriber.cpp

run:
	./PubSub_Platform